title: Shengnan (Pinker) Yao
logo: Shengnan Yao.png
#description: Shengnan (Pinker) Yao is a PhD student and research assistant at the News & Media Research Centre at the University of Canberra. She is also the scholarship recipient for an ARC project - the Rise of Mistrust: Digital platforms and Trust in News Media. Her research uses a mixed-method approach and focuses on trust in news media among Australian multicultural communities.
show_downloads: False
theme: jekyll-theme-minimal
