title: Shengnan (Pinker) Yao
logo: Pinker_Yao_Profile.JPG
description: PhD candidate and Research Associate at the News and Media Research Centre, University of Canberra. Researching news trust, multicultural audiences, migration, belonging and social cohesion.
show_downloads: False
theme: jekyll-theme-minimal
